#!/bin/bash

exec 2>&1

VOLUME_HOME="/var/lib/mysql"
find ${VOLUME_HOME} ! -user lo-daemon -exec chown lo-daemon. {} \;
find /var/log/mysql ! -user lo-daemon -exec chown lo-daemon. {} \;
chown -R lo-daemon. /var/run/mysqld/

if [[ ! -d ${VOLUME_HOME}/mysql ]]; then
	echo "=> An empty or uninitialized MySQL volume is detected in ${VOLUME_HOME}"
	echo "=> Installing MySQL ..."
	mysql_install_db
	echo "=> Done!"

	if [ -f /create_mysql_admin_user.sh ]; then
	   /create_mysql_admin_user.sh
	fi

else
	echo "=> Using an existing volume of MySQL"
fi

exec chpst -u lo-daemon /usr/sbin/mysqld --console
