#!/bin/bash

GOGO_SHELL_VERSION=0.12.0

mkdir -p /services/longback-daemon/runtime/shell
wget --no-check-certificate --no-cookies -O /services/longback-daemon/runtime/shell/org.apache.felix.org.apache.felix.gogo.shell-${GOGO_SHELL_VERSION}.jar http://172.17.10.31:8081/nexus/service/local/artifact/maven/redirect?r=public\&g=org.apache.felix\&a=org.apache.felix.gogo.shell\&e=jar\&v=${GOGO_SHELL_VERSION}

sv stop /etc/sv/longackd

cd /etc/sv

/services/longbackd